# Generated by Django 3.0.2 on 2020-02-01 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='officer',
            name='aval',
            field=models.BooleanField(default=True),
        ),
    ]
