# Generated by Django 3.0.2 on 2020-02-01 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officer', '0002_officer_aval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officer',
            name='officer_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
