# Generated by Django 3.0.2 on 2020-02-01 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officer', '0003_auto_20200201_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='officer',
            name='mrn',
            field=models.CharField(default='NILL', max_length=30),
        ),
    ]
