# Generated by Django 3.0.2 on 2020-02-02 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('officer', '0004_officer_mrn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='officer',
            name='mrn',
        ),
    ]
