# Generated by Django 3.0.2 on 2020-01-19 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('officer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('spouse', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField()),
                ('phone', models.IntegerField()),
                ('blood_group', models.CharField(max_length=30)),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('category', models.CharField(max_length=30)),
                ('registration_history', models.CharField(max_length=30)),
                ('p_image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('medical_instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='officer.Officer')),
            ],
        ),
    ]
