# Generated by Django 3.0.2 on 2020-02-01 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_auto_20200201_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='aadhaar',
            field=models.CharField(default='NILL', max_length=30),
        ),
    ]
