# Generated by Django 3.0.2 on 2020-02-03 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_auto_20200201_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='p_image',
            field=models.ImageField(default='default.jpg', upload_to='../main/static/main/profile_pics'),
        ),
    ]
