# Generated by Django 3.0.2 on 2020-02-05 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0008_patient_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='p_image',
        ),
    ]
