# Generated by Django 3.0.2 on 2020-02-05 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0009_remove_patient_p_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='p_image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
